## Numpy

In [1]:
!pip install numpy


[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


### Arrays NumPy

In [2]:
import numpy as np

array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


### Operações Matemáticas

Se você tentar adicionar um número a todos os elementos de uma lista, você receberá um erro.

In [3]:
lista = [1,2,3,4,5]
nova_lista = lista + 1
print(nova_lista)

TypeError: can only concatenate list (not "int") to list

Se eu quisesse fazer isso, teria que ser obrigado a criar um "For" e passar entre cada elemento da lista

In [4]:
nova_lista = []

for numero in lista:
    nova_lista.append(numero + 1)
print(nova_lista)

[2, 3, 4, 5, 6]


Com um array NumPy, você pode adicionar (ou subtrair, multiplicar, dividir) um número a todos os elementos de uma vez. Bem mais eficiente. Evita criar for

In [2]:
import numpy as np

array = np.array([1,2,3,4,5])
novo_array = array + 1
print(novo_array)
array_mult = array * 10
print(array_mult)
array_quadrado = array **2
print(array_quadrado)

[2 3 4 5 6]
[10 20 30 40 50]
[ 1  4  9 16 25]


### Desempenho

Para grandes quantidades de dados, os arrays NumPy são significativamente mais eficientes em termos de memória e desempenho do que as listas Python.

In [10]:
import numpy as np
import time

# crie uma lista e array com 10 milhões de números
lista = list(range(1, 10_000_001))
array = np.array(range(1, 10_000_001))

#calcule a soma de todos os números na Lista
inicio = time.time()
soma_lista = sum(lista)
fim = time.time()
print(f'Tempo para somar todos os números na lista: {fim - inicio} segundos')

#calcule a soma de todos os números no Array
inicio = time.time()
soma_array = np.sum(array)
fim = time.time()
print(f'Tempo para somar todos os números no array: {fim - inicio} segundos')

Tempo para somar todos os números na lista: 0.05177617073059082 segundos
Tempo para somar todos os números no array: 0.005994319915771484 segundos


### Conhecendo um array: indexação e slice

In [11]:
print(array[0])

1


Slicing: tira uma fatia (o último indice não é incluido, lembre-se disso)

In [3]:
print(array[1:4])

[2 3 4]


In [4]:
print(array[0:-1])

[1 2 3 4]


In [ ]:
print(array[0:-1:2]) #O último valor é o passo, ele pula de 2 em 2 nesse caso

[1 3]


In [6]:
print(array[0::2])

[1 3 5]


In [ ]:
print(array[::2]) #Não é obrigado a colocar o zero como na célula acima, ele já pega todo o array de 2 em 2

[1 3 5]


In [ ]:
print(array[ : : ]) #1° posição vazia significa que pega desde o início, a 2° significa até o fim, a 3° que o passo = 1

[1 2 3 4 5]


In [ ]:
print(array[::-1]) #Vai do inicio ao fim, mas voltando (Passo = -1)

[5 4 3 2 1]


### Aplicações do dia a dia
Suponhamos que trabalhamos em uma empresa que tem os preços de diferentes produtos em uma lista. Queremos aumentar o preço dos produtos em 10%, com NumPy isso é simples

In [10]:
#Preço dos produtos
precos = np.array([20, 25, 30, 35, 40])

#Aumentar os preços em 10% (ex: ajuste de inflação)
precos_novos = precos * (1 + 0.1)
print(precos_novos)

[22.  27.5 33.  38.5 44. ]


### np.sum()
soma os elementos de um Array. Exemplo útil: Somar todas as vendas de um dia

In [11]:
# Vendas do dia
vendas = np.array([200, 220, 250, 210, 300])

# Somar todas as vendas
print(np.sum(vendas))

1180


### np.mean()
Calcula a média de um Array. Exemplo útil: Calcular a média das vendas diárias em uma semana

In [14]:
#Vendas diárias em uma semana 
vendas = np.array([200, 220, 250, 210, 300, 280, 230])

# Calcular a média de vendas
media_vendas = np.mean(vendas)
print(f'A média de vendas foi {media_vendas:.2f}')

A média de vendas foi 241.43


#### np.max() e np.min()

In [15]:
# Preço dos produtos
precos = np.array([20,25,30,35,40])

# Encontrar o produto mais caro e mais barato
produto_mais_caro = np.max(precos)
produto_mais_barato = np.min(precos)

print(f'O porduto mais caro da loja custa R${produto_mais_caro}')
print(f'O produto mais barato da loja custa R${produto_mais_barato}')

O porduto mais caro da loja custa R$40
O produto mais barato da loja custa R$20


#### np.sort()

In [16]:
# Vendas diárias
vendas = np.array([200,220,250,210,300])

# Ordenar as vendas
vendas_ordenadas = np.sort(vendas)
print(vendas_ordenadas)

[200 210 220 250 300]


#### np.dot()
Usada para calcular o produto escalar de dois arrays. Por exemplo, em uma empresa de varejo, você pode querer calcular o valor total de vendas, dado o número de cada produto vendido e o preço de cada produto.

In [ ]:
# Número de produtos vendidos
quantidades = np.array([10, 20, 30, 40])

# Preços dos produtos
precos = np.array([5,10,15,20])

# Calcular o valor total de vendas
print(np.sum(quantidades * precos)) #Uma forma de fazer
print(np.dot(quantidades, precos)) #mais simples com np.dot

1500
1500


### Exercícios NumPy

#### 1) Você é um gerente de vendas e tem os dados de vendas de um produto para os últimos 7 dias em uma lista: `[127, 90, 201, 150, 210, 220, 115]`. Calcule a média de vendas durante a semana.

In [22]:
import numpy as np
dados = [127, 90, 201, 150, 210, 220, 115]
media_vendas = np.mean(dados)
print(f'A média de vendas desse produto na semana foi {media_vendas} por dia')

A média de vendas desse produto na semana foi 159.0 por dia


#### 2) Você é um analista financeiro e tem os preços de fechamento diário de uma ação para a última semana em um array NumPy: `precos = np.array([31.40, 31.25, 30.95, 31.20, 31.60, 31.50])`. Calcule o preço máximo, mínimo e a variação de preço durante a semana.

In [26]:
precos = np.array([31.40, 31.25, 30.95, 31.20, 31.60, 31.50])
preco_maximo = np.max(precos)
preco_minimo = np.min(precos)
variacao_preco = preco_maximo - preco_minimo
print(f'O preço máximo da ação na última semana foi de R${preco_maximo:.2f}, e o preço mínimo de R${preco_minimo}, sendo assim, a variação de preco foi R${variacao_preco:.2f}')

O preço máximo da ação na última semana foi de R$31.60, e o preço mínimo de R$30.95, sendo assim, a variação de preco foi R$0.65


#### 3) Sua loja vendeu em um dia 5 unidades do *Produto A*, 3 unidades do *Produto B* e 2 unidades do *Produto C*. Os preços dos produtos são, respectivamente, 100, 200 e 50 reais. Calcule o total de vendas do dia.

In [27]:
import numpy as np

quantidades = np.array([5, 3, 2])
precos = np.array([100, 200, 50])

total_vendas_dia = np.dot(quantidades, precos)
print(f'O total de vendas no dia foi de R${total_vendas_dia}')

O total de vendas no dia foi de R$1200


### Números aleatórios e estatística básica

In [ ]:
# crie um gerador de números aleatórios.
import numpy as np
rng = np.random.default_rng()
print(rng)

numero_aleatorio = rng.random() #Vai sempre gerar números entre zero e um, mas você pode adicionar, multiplicar e etc para alterar isso
print(numero_aleatorio)

Generator(PCG64)
0.47799556193978554


In [4]:
array_aleatorio = rng.random(3) * 100 #Agora vou ter números entre zero e cem
print(array_aleatorio)

[32.69867823 62.36843623 20.39206039]


### Cenário onde esses dados aleatórios podem ser úteis:
Vamos supor que a gente seja um analista de vendas em uma empresa e queira entender melhor o desempenho de um produto específico. No entanto, não temos acesso aos dados reais de vendas, então vamos gerar valores aleatórios para análise. Temos que tivermos eles, é só substituir na análise já estruturada

In [ ]:
# Gerar dados de vendas falsos para 30 dias 
# Vamos supor que as vendas de um produto podem variar de 50 a 200 por dia
# Pode definir uma seed para garantir que os resultados sejam reproduzíveis.
rng = np.random.default_rng(seed=0) #Toda pessoa que rodar esse código com esse mesmo valor, vai ter os mesmos números
dados_vendas = rng.integers(low=50, high=200, size=30) #Mínimo 50, máximo 200, tamanho 30
print(dados_vendas)

[177 145 126  90  96  56  61  52  76 171 147 186 125 140 195 159 144 131
 133 190  91 172 150  50 109 178 133  55 164 159]


Agora, podemos usar esses dados para várias análises. Por exemplo, dia com as vendas mais altas, mais baixas, ou a média de vendas durante o mês

In [23]:
print(f'Máximo de vendas nesse mês: {np.max(dados_vendas)}')
print(f'Dia com mais vendas: {np.argmax(dados_vendas) + 1}') #+1 por causa que estamos contanto dias, e a programação sempre conta a partir do 0, não queremos isso.
print(f'Mínimo de vendas nesse mês: {np.min(dados_vendas)}')
print(f'Dia com menos vendas: {np.argmin(dados_vendas) + 1}')
print(f'Média de vendas nesse mês: {np.mean(dados_vendas)}')

Máximo de vendas nesse mês: 195
Dia com mais vendas: 15
Mínimo de vendas nesse mês: 50
Dia com menos vendas: 24
Média de vendas nesse mês: 128.7


### Outras funções de estatística

Mediana

In [24]:
print(np.median(dados_vendas))

136.5


Percentil

In [ ]:
print(np.percentile(dados_vendas, 25)) #25% dos valores estão abaixo do valor 92.25

92.25


Desvio Padrão (O quão disperso os valores estão da média)

In [27]:
print(np.std(dados_vendas))

44.330689144203475


Variância (Outra medida de dispersão, é o quadrado do desvio padrão)

In [28]:
print(np.var(dados_vendas))

1965.21


### Filtros e np.where()

In [ ]:
#Salário dos funcionários
salarios = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])

#Calcular a média salarial
media_salarial = np.mean(salarios)

print(media_salarial)

#Identificar funcionários com salários acima da média
funcionarios_acimamedia = np.where(salarios > media_salarial)
print(salarios[funcionarios_acimamedia]) #NumPy também aceita que você passe Arrays como Indice
#Outros métodos dentro do Array
print(salarios[salarios > media_salarial])
print(salarios[salarios >= 4000])

print(np.where(salarios > media_salarial, 'acima da média', 'abaixo da média')) #O Where pode ser bem mais trabalhado, (expressão, condição se verdadeiro, se falso)

salarios_bonus = np.where(salarios < media_salarial, salarios * 1.1, salarios) #Aumento de 10% pra quem tem o salário abaixo da média
print(salarios_bonus)

3714.285714285714
[4000 4500 4000 5000]
[4000 4500 4000 5000]
[4000 4500 4000 5000]
['abaixo da média' 'abaixo da média' 'acima da média' 'abaixo da média'
 'acima da média' 'acima da média' 'acima da média']
[3300. 3850. 4000. 2200. 4500. 4000. 5000.]
(array([0, 1, 2, 5]),)


In [39]:
salarios_ajustados = np.where((salarios >= 3000) & (salarios <= 4500), salarios * 1.05, salarios)
print(salarios_ajustados)

[3150. 3675. 4200. 2000. 4725. 4200. 5000.]


In [40]:
print(np.where((salarios_ajustados < 3000) | (salarios_ajustados > 4500)))

(array([3, 4, 6]),)


In [41]:
print(np.where((salarios_ajustados < 3000) | (salarios_ajustados > 4500), salarios_ajustados * 1.1, salarios_ajustados))

[3150.  3675.  4200.  2200.  5197.5 4200.  5500. ]


#### Você é um analista de RH e tem os salários de todos os funcionários da sua empresa em um array NumPy. Seu trabalho é identificar quantos funcionários ganham acima da média.

In [ ]:
import numpy as np

salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])
media_salarial = np.mean(salarios)

#Quantos ganham acima da média
funcionarios_acima_media = np.sum(salarios > media_salarial) #True = 1, False = 0, ele soma os Trues (acima da média nesse caso)
print(f'{funcionarios_acima_media} funcionários possuem salários acima da média')

9
5 funcionários possuem salários acima da média


#### Outras formas de fazer contagem

In [46]:
print(np.count_nonzero(salarios > media_salarial))

5


In [47]:
print(np.unique(salarios > media_salarial))

[False  True]


In [49]:
print(np.unique(salarios > media_salarial, return_counts = True))

(array([False,  True]), array([4, 5]))


#### Criando 20 valores fictícios com a mesma faixa anterior, tomando cuidado de outras pessoas gerarem os mesmos valores (seed)

In [51]:
rng = np.random.default_rng(seed = 42)

salarios_geraddos = rng.integers(low=min(salarios), high= max(salarios), size = 20)
print(salarios_geraddos)

[2249 4167 3832 3228 3212 4404 2240 3952 2564 2263 3474 4731 4060 4131
 4008 4200 3437 2358 4351 3261]


In [ ]:
rng = np.random.default_rng(seed = 42)

salarios_geraddos = rng.integers(low=min(salarios), high= max(salarios), size = 20, endpoint=True) #endpoint = True, inclui o valor máximo, se não ele não entra, igual o indice
print(salarios_geraddos)

In [52]:
#as funções estatísticas também podem ser usadas como métodos dos arrays
print(salarios_geraddos.min())
print(salarios_geraddos.max())
print(salarios_geraddos.mean())

2240
4731
3506.1


#### Você é um engenheiro de produção e tem os tempos de ciclo (em minutos) de uma linha de produção em um array NumPy. Seu trabalho é identificar quaisquer tempos de ciclo que estão dois desvios padrão acima ou abaixo da média

In [58]:
import numpy as np

tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])
media = np.mean(tempos_ciclo)
desvio_padrao = np.std(tempos_ciclo)
print(media)
print(desvio_padrao)

condicao = (tempos_ciclo > media + 2 * desvio_padrao) | (tempos_ciclo < media - 2 * desvio_padrao)
anomalias = np.where(condicao)
print(tempos_ciclo[anomalias])
# Print mais elaborado
print(f'Os tempos que estão na condição pedida são {tempos_ciclo[anomalias]}')

5.8
0.592546294487706
[7.2]
Os tempos que estão na condição pedida são [7.2]


Para pegar o contrário dessa condição (Ou seja, a parte que está entre os 2 desvios padrões acima e abaixo da média) usamos o ~ (negação da condição)

In [60]:
print(~condicao) #Ele simplesmente inverteu 
print(tempos_ciclo[~condicao])

#No Python padrão existe o NOT ao invés de ~ no NumPy (Muitas coisas do Python padrão tem no NumPy, só é mudado a simbologia)

[ True  True  True  True  True  True  True False  True]
[5.5 5.7 5.9 6.  5.8 5.6 5.7 4.8]


Bonus (Usando o normal, Distribuição Normal ou Gaussiana) para curva de probabilidade em forma de sino, o valor central é a média, na esquerda é a média - desvio padrão, na direita, média + desvio padrão

In [61]:
rng = np.random.default_rng(seed=0)
tempos_gerados = rng.normal(loc=media, scale=desvio_padrao, size=10)
print(tempos_gerados)

[5.87450098 5.72172175 6.17948007 5.86215818 5.4825911  6.01426181
 6.57268039 6.36118932 5.38300429 5.0501792 ]


In [ ]:
condicao = ((tempos_gerados > tempos_gerados.mean() + 2 * tempos_gerados.std()) | (tempos_gerados < tempos_gerados.mean() - 2 * tempos_gerados.std()))
print(np.where(condicao))
print(tempos_gerados[condicao]) #Não tem dados de desvio padrão 2 pontos acima ou abaixo da média

(array([], dtype=int64),)
[]


#### np.reshape()
Muda o formato de um array. Por exemplo, se temos dados de vendas para 2 semanas e queremos reorganizar em uma matriz de 2x7 (2 semanas, 7 dias por semana)

In [ ]:
import numpy as np
# Vendas diárias para 2 semanas
vendas = np.array([200,220,250,210,300,280,230,210,220,240,230,210,280,220])
# Reorganizar os dados em uma matriz de 2x7 (útil se quisermos analisar cada semana separadamente)
vendas_reshaped = np.reshape(vendas, (2, 7)) #2 dimensões de 7 elementos (2 linhas e 7 colunas)
print(vendas_reshaped)


[[200 220 250 210 300 280 230]
 [210 220 240 230 210 280 220]]


In [5]:
#Array antes do reshape
print(vendas)
print(vendas.ndim) #Uma única dimensão de valores
print(vendas.shape)

print('-' * 50)
#Array depois do reshape
print(vendas_reshaped)
print(vendas_reshaped.ndim)
print(vendas_reshaped.shape)

[200 220 250 210 300 280 230 210 220 240 230 210 280 220]
1
(14,)
--------------------------------------------------
[[200 220 250 210 300 280 230]
 [210 220 240 230 210 280 220]]
2
(2, 7)


#### Outras operações

In [10]:
print(vendas_reshaped[0])
print(vendas_reshaped[1])
print(vendas_reshaped[0][0])
print(vendas_reshaped[1][0])
print('-'*50)
print(vendas_reshaped.sum())
print(f'Soma do primeiro eixo: {vendas_reshaped.sum(axis=0)}') #Soma empilhando (cada coluna)
print(f'Soma do segundo eixo: {vendas_reshaped.sum(axis=1)}') #Soma da primeira e segunda linha

[200 220 250 210 300 280 230]
[210 220 240 230 210 280 220]
200
210
--------------------------------------------------
3300
Soma do primeiro eixo: [410 440 490 440 510 560 450]
Soma do segundo eixo: [1690 1610]


#### Você também pode pedir para que o NumPy divida para você (-1)

In [ ]:
alterar_vendas = np.reshape(vendas, (2, -1)) #Vai dividir por 2 (como tem 14 valores, vai ficar 7 colunas), o contrário também funciona (-1, 7), divide por 7
print(alterar_vendas)

[[200 220 250 210 300 280 230]
 [210 220 240 230 210 280 220]]


#### Exemplo
Considere que uma loja funciona de segunda a sábado, independentemente de feriados. Nos últimos 30 dias, teve o menor volume de vendas sendo 20 e o maior 200. Crie uma simulação das vendas desses últimos 30 dias, separados por semanas. Calcule:
- Total de vendas por semana
- A média de vendas por semana
- A média de vendas por dia da semana

In [12]:
import numpy as np
rng = np.random.default_rng(seed=42)
vendas = rng.integers(low=20, high=200, size= 30, endpoint=True) #endpoint inclui o valor máximo, se não, ele não entra, igual o indice
vendas_semanais = np.reshape(vendas, (-1,6))
print(vendas_semanais)

[[ 36 160 138  99  98 175]
 [ 35 146  56  37 115 196]
 [153 157 149 162 112  43]
 [171 101 110  87  53 187]
 [161 136  92 168 118 100]]


In [13]:
#Tem como fazer direto no gerador
vendas = rng.integers(low=20, high=200, size=(5,6), endpoint=True)
print(vendas)

[[101  61  36 120 180  31]
 [175 169  70 134  49 157]
 [146  84  32 195 100 181]
 [142 160 157  55  85 104]
 [110  27 118  47 154 143]]


In [ ]:
# Total de vendas por semana
total_vendas_semana = vendas_semanais.sum(axis=1)
print(total_vendas_semana)
# Média de vendas por semana
media_semanal_vendas = vendas_semanais.mean(axis=1)
print(media_semanal_vendas)
# Média de vendas por dia da semana
media_dia_semana = vendas_semanais.mean(axis=0)
print(media_dia_semana)

#Você como analista, pode até recorrer a equipe de vendas e perguntar porque sexta-feira é o dia que menos vende, tem algo que vocês estão fazendo de diferente? Vocês fazem 
#promoções nos outros dias que não tem na sexta? Será que a gente poderia fazer promoções na sexta?

[706 585 776 709 775]
[117.66666667  97.5        129.33333333 118.16666667 129.16666667]
[111.2 140.  109.  110.6  99.2 140.2]


### Exercícios NumPy
Você é um gerente de vendas e tem os dados de vendas de três produtos diferentes (Produto A, B e C) para os últimos 5 dias em um array 2D NumPy. Cada linha do array representa um produto e cada coluna representa um dia. Seu trabalho é calcular as vendas totais para cada produto e para cada dia. 

In [27]:
import numpy as np

vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])

# Calcular as vendas totais para cada produto
total_vendas_produtos = vendas.sum(axis= 1)
print(f'Vendas totais do Produto A: {total_vendas_produtos[0]}')
print(f'Vendas totais do Produto B: {total_vendas_produtos[1]}')
print(f'Vendas totais do Produto C: {total_vendas_produtos[2]}')
# Vendas totais em cada dia
print('-' * 35)
total_vendas_dia = vendas.sum(axis=0)
for i in range(5):
        print(f'Vendas totais para o Dia {i + 1}: {total_vendas_dia[i]}')

Vendas totais do Produto A: 325
Vendas totais do Produto B: 433
Vendas totais do Produto C: 368
-----------------------------------
Vendas totais para o Dia 1: 207
Vendas totais para o Dia 2: 225
Vendas totais para o Dia 3: 216
Vendas totais para o Dia 4: 234
Vendas totais para o Dia 5: 244


##### Você é um analista de dados em uma empresa e conduziu uma pesquisa de satisfação do cliente durante uma semana. Você pedu aos clientes para classificar seu nível de satisfação com o serviço em uma escala de 0 a 10. Você coletou respostas de 30 clientes por dia durante 7 dias, resultando em 210 respostas.

No entanto, os dados que você recebeu estão em um array 1D de 210 elementos. Reorganize os dados de forma a ter respostas por dia e faça uma análise descritiva básica, calculando a média geral de satisfação e a média diária.

In [28]:
import numpy as np

#Considere os seguintes dados aleatórios como início
rng = np.random.default_rng(seed=42)
respostas = rng.integers(low=0, high=10, size=210, endpoint=True)
print(respostas)

[ 0  8  7  4  4  9  0  7  2  1  5 10  8  8  7  8  5  1  9  4  5  4  2 10
  8  7  4  9  5  4  4  2  1  6  9  0  9  9  3  6  1  8  7  3  0 10  4  9
  7  8  8  2  4  5  5  0  6  1  8  7 10  8  4 10  4  3  9  4  0  5  8  2
  5  1  7  5  3  2  6  7 10  4  1  9  6  7  1  3  8  9  4  8  9  4  9  3
  2  7  7  1  9  2  8  0  8  8  8  7  5  7  3  8  6  5  5  6  0  1  2  1
  4  7  7  5  9  6  0  8  6  6  6  6  0  6  8  3  6  0  3  4 10  2  3  4
 10  9  0  2  9  0  9  3 10  3  4  7  1  6  5  8 10  7  4  4  4  8  3  1
  3  0  1  0  8  7  7  5  7  1  9  5 10  1  5  7  5  4  1  4  2  3  7  6
  6  3 10  0  3  1  3 10  4  9  5  7  5  2  8 10  2  8]


In [29]:
#Vamos fazer um reshape
respostas_ordenadas = np.reshape(respostas, (7, 30)) #7: colunas, 30: linhas
print(respostas_ordenadas)

[[ 0  8  7  4  4  9  0  7  2  1  5 10  8  8  7  8  5  1  9  4  5  4  2 10
   8  7  4  9  5  4]
 [ 4  2  1  6  9  0  9  9  3  6  1  8  7  3  0 10  4  9  7  8  8  2  4  5
   5  0  6  1  8  7]
 [10  8  4 10  4  3  9  4  0  5  8  2  5  1  7  5  3  2  6  7 10  4  1  9
   6  7  1  3  8  9]
 [ 4  8  9  4  9  3  2  7  7  1  9  2  8  0  8  8  8  7  5  7  3  8  6  5
   5  6  0  1  2  1]
 [ 4  7  7  5  9  6  0  8  6  6  6  6  0  6  8  3  6  0  3  4 10  2  3  4
  10  9  0  2  9  0]
 [ 9  3 10  3  4  7  1  6  5  8 10  7  4  4  4  8  3  1  3  0  1  0  8  7
   7  5  7  1  9  5]
 [10  1  5  7  5  4  1  4  2  3  7  6  6  3 10  0  3  1  3 10  4  9  5  7
   5  2  8 10  2  8]]


In [35]:
#Vamos calcular agora a média geral e diária de satisfação
media_geral = respostas_ordenadas.mean()
print(f'{media_geral:.2f}')
print('-' * 30)
media_diaria_respostas = respostas_ordenadas.mean(axis=1) #eixo 0 desce, eixo 1 vai na horizontal (linhas)
print(media_diaria_respostas)

5.15
------------------------------
[5.5        5.06666667 5.36666667 5.1        4.96666667 5.
 5.03333333]
